/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   CameraIP.h
 * Author: moi
 *
 * Created on 17 de diciembre de 2017, 19:01
 */

#ifndef CAMERAIP_H
#define CAMERAIP_H

#include "Player.h"

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VideoStreamPlayer_VideoStreamPlayer */

#ifndef _Included_VideoStreamPlayer_VideoStreamPlayer
#define _Included_VideoStreamPlayer_VideoStreamPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VideoStreamPlayer_VideoStreamPlayer
 * Method:    openStream
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_videoplayer_VideoStreamPlayer_openStream
  (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_videoplayer_VideoStreamPlayer_objectDetectionEnabled
  (JNIEnv *, jclass,bool ptr);

#ifdef __cplusplus
}
#endif
#endif


class CameraIP {
public:
    Player  *ptr;
    void openInputStream(char       *str);
    void setObjectDetection();
private:

};

#endif /* CAMERAIP_H */

